# Generated by Django 4.2 on 2023-06-06 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("father_name", models.CharField(max_length=100)),
                ("father_number", models.CharField(max_length=10)),
                ("mother_name", models.CharField(max_length=100)),
                ("mother_number", models.CharField(max_length=10)),
                ("student_number", models.CharField(max_length=10)),
                ("gmail", models.EmailField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="studentdetailmodel",
            name="branch",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="studentdetailmodel",
            name="contact_info",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_detail_contact_info",
                to="student.studentcontactinfo",
            ),
        ),
    ]
