# Generated by Django 4.2 on 2023-06-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_studentcontactinfo_alter_studentdetailmodel_branch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressDetailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pincode", models.IntegerField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="studentdetailmodel",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_detail_address_info",
                to="student.addressdetailmodel",
            ),
        ),
    ]
