# Generated by Django 4.2 on 2023-06-07 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_assignment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="contact",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="username",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofilemodel",
            name="bio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="userprofilemodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofilemodel",
            name="followers",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofilemodel",
            name="following",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofilemodel",
            name="posts",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofilemodel",
            name="user_info",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profile_model_user_info",
                to="user_assignment.usermodel",
            ),
        ),
        migrations.AddField(
            model_name="userprofilemodel",
            name="post_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profile_model_post_info",
                to="user_assignment.userpostmodel",
            ),
        ),
    ]
