# Generated by Django 4.2 on 2023-06-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_assignment", "0004_userpostmodel_likes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofilemodel",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_profile_followers",
                to="user_assignment.usermodel",
            ),
        ),
        migrations.AlterField(
            model_name="userprofilemodel",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_profile_following",
                to="user_assignment.usermodel",
            ),
        ),
    ]
